@extends('layouts.admin')

@section('title', 'AI Blog Generator')

@section('content')

    <div class="row g-4">
        <div class="col-lg-5">
            <div class="card border-0 shadow-sm">
                <div class="card-body p-4">
                    <h6 class="fw-bold mb-3"><i class="bi bi-stars text-primary"></i> Generate a Blog Post</h6>
                    <p class="text-secondary small">
                        Enter a topic and let AI draft a full blog post. You'll be able to review and edit it before publishing.
                    </p>

                    @if (session('error'))
                        <div class="alert alert-danger">{{ session('error') }}</div>
                    @endif

                    <form action="{{ route('admin.ai-blog.generate') }}" method="POST">
                        @csrf
                        <div class="mb-3">
                            <label class="form-label">Blog Topic</label>
                            <input type="text" name="topic" class="form-control @error('topic') is-invalid @enderror"
                                   placeholder="e.g. 5 Signs Your Roof Needs Repair"
                                   value="{{ old('topic', $topic ?? '') }}">
                            @error('topic') <div class="invalid-feedback">{{ $message }}</div> @enderror
                        </div>

                        <div class="mb-3">
                            <label class="form-label">Tone</label>
                            <select name="tone" class="form-select">
                                <option value="professional">Professional</option>
                                <option value="friendly">Friendly</option>
                                <option value="technical">Technical</option>
                                <option value="persuasive">Persuasive</option>
                            </select>
                        </div>

                        <button type="submit" class="btn btn-primary w-100">
                            <i class="bi bi-magic"></i> Generate with AI
                        </button>
                    </form>
                </div>
            </div>
        </div>

        <div class="col-lg-7">
            @if (! empty($generated))
                <div class="card border-0 shadow-sm">
                    <div class="card-body p-4">
                        <h6 class="fw-bold mb-3"><i class="bi bi-eye text-primary"></i> Review &amp; Save Draft</h6>
                        <p class="text-secondary small mb-4">
                            This was generated by AI — review and edit before saving. It will be saved as a draft
                            unless you check "Publish".
                        </p>

                        <form action="{{ route('admin.ai-blog.save') }}" method="POST">
                            @csrf

                            <div class="mb-3">
                                <label class="form-label">Category</label>
                                <select name="category_id" class="form-select">
                                    <option value="">Select category</option>
                                    @foreach ($categories as $category)
                                        <option value="{{ $category->id }}">{{ $category->name }}</option>
                                    @endforeach
                                </select>
                            </div>

                            <div class="mb-3">
                                <label class="form-label">Title</label>
                                <input type="text" name="title" class="form-control" value="{{ $generated['title'] }}">
                            </div>

                            <div class="mb-3">
                                <label class="form-label">Excerpt</label>
                                <textarea name="excerpt" rows="2" class="form-control">{{ $generated['excerpt'] }}</textarea>
                            </div>

                            <div class="mb-3">
                                <label class="form-label">Content</label>
                                <textarea name="content" rows="14" class="form-control">{{ $generated['content'] }}</textarea>
                            </div>

                            <div class="form-check mb-3">
                                <input type="hidden" name="is_published" value="0">
                                <input type="checkbox" name="is_published" value="1" class="form-check-input" id="is_published">
                                <label class="form-check-label" for="is_published">Publish immediately</label>
                            </div>

                            <button type="submit" class="btn btn-primary px-4">
                                <i class="bi bi-save"></i> Save Blog Post
                            </button>
                        </form>
                    </div>
                </div>
            @else
                <div class="card border-0 shadow-sm h-100">
                    <div class="card-body p-5 text-center d-flex flex-column align-items-center justify-content-center text-secondary">
                        <i class="bi bi-stars fs-1 mb-3"></i>
                        <p class="mb-0">Your generated draft will appear here for review.</p>
                    </div>
                </div>
            @endif
        </div>
    </div>

@endsection
